apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lyeo0sogi-go
  janus-idp.io/tekton: lyeo0sogi-go
  backstage.io/kubernetes-id: lyeo0sogi-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lyeo0sogi-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
