apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lyeo0sogi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lyeo0sogi-go 
  name: lyeo0sogi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lyeo0sogi-go 
